### ISSUE TITLE
Мод не работает

### ISSUE THREAD

**Issue by pereherovercheniy** [lexlaw2/USMilPatch#3]
ЗДАРОВА, мод чето не работает, ставлю, но глючит, скинь гайд как правильно поставить

**Comment by lexlaw2** [comment]
и вам не болеть
странно что патч вас заинтересовал
его цель убрать зависимость  это мода https://steamcommunity.com/sharedfiles/filedetails/?id=579942493
от CUPа, не нарушая требования автора. соответственно для его работы нужен установленный US Military Mod
вы уверены, что вам именно это и надо?
